### PR TITLE
[SKIP-1015] Add wordy deprecation warnings

### PR DESCRIPTION
**Pull request by anderssonw**
Another alternative is creating a separate job instead of having it in a step on every action.

See https://github.com/kartverket/shipwreck/actions/runs/4511630410/jobs/7944027843 for how it looks

### CODE REVIEW

**Review by lislei — APPROVED** [review]

**Comment by esphen** [comment]
I doubt people are going to see this if it is in a separate step? I had to look for it even though I know to look. 

Could writing this as an [error message](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) help?

We can also consider appending it to the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

**Comment by anderssonw** [comment]
> I doubt people are going to see this if it is in a separate step? I had to look for it even though I know to look.
> 
> Could writing this as an [error message](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) help?
> 
> We can also consider appending it to the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

Oooh I wasn't aware of these features. That's indeed a better solution. Looking into it :) @esphen

**Comment by anderssonw** [comment]
https://github.com/kartverket/shipwreck/actions/runs/4529789373

How about now @esphen :)

**Review by esphen — APPROVED** [review]
Kult :)

**Pull request merged**
